#!/bin/bash

XRANDR=$(xrandr)

HDMI=$(egrep -o "HDMI[0-9]{1,}" <<<"$XRANDR")
LVDS=$(egrep -o "LVDS[0-9]{1,}" <<<"$XRANDR")
VGA=$(egrep -o "VGA[0-9]{1,}" <<<"$XRANDR")

HDMI_CON=$(egrep -o "$HDMI connected [0-9]{1,}x[0-9]{1,}" <<<"$XRANDR")
LVDS_CON=$(egrep -o "$LVDS connected [0-9]{1,}x[0-9]{1,}" <<<"$XRANDR")
VGA_CON=$(egrep -o "$VGA connected [0-9]{1,}x[0-9]{1,}" <<<"$XRANDR")

# if currently displaying external AND internal
#    switch to external
# else if currentyl displaying external AND NOT internal
#    switch to internal
# else ( currently displaying internal )
#    switch to external AND internal
# endif


if [[ -n $HDMI_CON && -n $LVDS_CON ]]
then
  echo "HDMI+LVDS connected"
  xrandr --output "$LVDS" --off --output "$HDMI" --auto
elif [[ -n $HDMI_CON ]]
then
  echo "HDMI connected"
  xrandr --output "$LVDS" --auto --output "$HDMI" --off 
else
  echo "LVDS connected"
  xrandr --output "$LVDS" --auto --output "$HDMI" --auto
fi
# 12
# alsa_output.pci-0000_00_1b.0.hdmi-stereo
# 8
# alsa_output.pci-0000_00_1b.0.analog-stereo
